### ISSUE TITLE
Body Element

### ISSUE THREAD

**Issue by cyouh95** [aboseman1/Cozy#3]
The structure of an HTML document is:
```html
<!DOCTYPE html>
<html>
  <head> ... </head>
  <body> ... </body>
</html>
```

The `head` element contains all the metadata of the page (ie. `title` of page, links to scripts and stylesheets, etc.), while the `body` element should contain everything that is actually visible on the webpage. Thus, make sure your [header](https://github.com/aboseman1/Cozy/blob/master/index.html#L9-L22) element is contained within the `body` element (ie. placed after line 25).

**Comment by aboseman1** [comment]
Got it!
