### ISSUE TITLE
Body Default Margin

### ISSUE THREAD

**Issue by cyouh95** [aboseman1/Cozy#4]
In most browsers, the `body` element has a `margin` of `8px` by default. This would explain the slight spacing you see around your page (for example, the space above your navigation bar as you scroll). To get rid of this, you could specify `margin: 0` for your [body](https://github.com/aboseman1/Cozy/blob/master/css/style.css#L3-L7) element.

**Comment by aboseman1** [comment]
Got it! This is helpful as I was wondering how to get rid of that space as the top and on the sides of the page. This was also an effect of the fact that I had the Header outside of the body.
