### ISSUE TITLE
IDs to Create Hyperlinks

### ISSUE THREAD

**Issue by cyouh95** [aboseman1/Cozy#5]
Instead of using `class`es for each of main section containers on your page (ie. `.mission`, `.middle`, `.locations`) - you can use `id`s. That way, you will also be able to create hyperlinks (ie. in your navigation bar) to jump to that section of the page. For example:

HTML:

```html
<a href="#mission"><span>Mission</span></a>
```
https://github.com/aboseman1/Cozy/blob/master/index.html#L17

```html
<div id="mission" ... >
    ...
</div>
```
https://github.com/aboseman1/Cozy/blob/master/index.html#L27

CSS:

```css
#mission {
  ...
}
```
https://github.com/aboseman1/Cozy/blob/master/css/style.css#L83

**Comment by aboseman1** [comment]
This also makes sense. One thing that I commonly have an issue with is truly understanding when the best time to use ID's versus classes.
